version: "3.2"
services:
  postgres:
    image: postgres:latest
    container_name: postgrescomunik
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=postgres
         - POSTGRES_DB=postgres
    restart: unless-stopped
    networks:
      postgres-network:
         aliases:
           - postgrescomunik

# APP*****************************************

  comunik:
    image: magalu/comunik:latest
    container_name: comunik
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    environment:
         - POSTGRESQL_PASSWORD=admin
         - POSTGRESQL_USERNAME=postgres
         - POSTGRESQL_HOST=postgrescomunik:5432
    networks:
      - postgres-network
         
volumes:
  postgres-data:
  
networks:
  postgres-network: